### ISSUE TITLE
BUG: Off-by-one error on ticket count in order form

### ISSUE THREAD

**Issue by thermokarst** [qiime2/workshops.qiime2.org#101]
When an admin sets up a new rate, the form displays `n-1` tickets available.

**Comment by jairideout** [comment]
@thermokarst does this card need to be on the Scrum board?

**Comment by thermokarst** [comment]
@jairideout: not at this time --- the solution is to set the rate capacity to `n+1`, which is an easy enough fix (and I think I am the only one impacted by this ATM).

**Comment by thermokarst** [comment]
Fixed in #105
