### ISSUE TITLE
ENH: admins should receive email upon registration

### ISSUE THREAD

**Issue by jairideout** [qiime2/workshops.qiime2.org#99]
Admins should be bcc'd on registration emails that are sent to participants.

**Comment by thermokarst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [asdf](https://trello.com/c/z5kHqq8Q/1-asdf)

**Comment by jairideout** [comment]
Huh? lol

**Comment by thermokarst** [comment]
Ahaahaha, I was playing with Trello earlier...

**Comment by jairideout** [comment]
![](https://cdn-images-1.medium.com/max/800/1*O4J8OYp4ITHnSsCZwhulew.png)
